// Generated by HybirdPB CodeGenerator(1.2.0). DO NOT EDIT!
// Generation date is 2018-08-08 15:54:41

package com.yqhd.wanandroid.launcher.request;

public class UserLoginPostReq {
    public String username = "doraemon";
    public String password = "123456789";
    public loginBean _requestBody;

}