// Generated by HybirdPB CodeGenerator(1.2.0). DO NOT EDIT!
// Generation date is 2018-08-08 15:54:41

package com.yqhd.wanandroid.launcher.request;

import com.alipay.mobile.framework.service.ext.annotation.CheckLogin;
import com.alipay.mobile.framework.service.annotation.OperationType;
import com.alipay.mobile.framework.service.annotation.SignCheck;

import com.yqhd.wanandroid.launcher.request.UserLoginPostReq;
   
public interface Yqhd_wanAndroid_01Client {

    @SignCheck
    @OperationType("com.yqhd.wanAndroid.login") 
    public String userLoginPost(UserLoginPostReq requestParam);


}