// Generated by HybirdPB CodeGenerator(1.2.0). DO NOT EDIT!
// Generation date is 2018-08-08 15:54:41

package com.yqhd.wanandroid.launcher.request.bean;


public class loginBean {
    public String username ;
    public String password ;

    public loginBean(String username, String password) {
        this.username = username;
        this.password = password;
    }
}