// Generated by HybirdPB CodeGenerator(1.2.0). DO NOT EDIT!
// Generation date is 2018-08-14 11:12:59

package com.yqhd.wanandroid.launcher.request.bean;


public class registerbean {
    public String username = "测试000001";
    public String password = "123456789";
    public String repassword = "123456789";

}