// Generated by HybirdPB CodeGenerator(1.2.0). DO NOT EDIT!
// Generation date is 2018-08-27 16:52:15

package com.yqhd.wanandroid.launcher.request.req;


public class ArticleListPageJsonGetReq {
    public Integer page;

}