// Generated by HybirdPB CodeGenerator(1.2.0). DO NOT EDIT!
// Generation date is 2018-08-14 11:12:59

package com.yqhd.wanandroid.launcher.request.req;


import com.yqhd.wanandroid.launcher.request.bean.registerbean;

public class UserRegisterPostReq {
    public registerbean _requestBody;

}