// Generated by HybirdPB CodeGenerator(1.2.0). DO NOT EDIT!
// Generation date is 2018-08-08 15:54:41

package com.yqhd.wanandroid.launcher.request.req;

import com.yqhd.wanandroid.launcher.request.bean.loginBean;

public class UserLoginPostReq {
    public loginBean _requestBody;
}